printWidth: 80
tabWidth: 2
semi: true
singleQuote: true
trailingComma: all
jsxSingleQuote: true
htmlWhitespaceSensitivity: strict
endOfLine: lf
arrowParens: always
plugins:
  - prettier-plugin-organize-imports
  - prettier-plugin-packagejson
