[workspace]
members = [
    "apps/*",
    "libs/*",
    "kits/*"
]
[workspace.dependencies]
clap = { version = "4.1.6", features = ["derive"] }
log = "0.4.16"
env_logger = "0.9.0"
figment = { version = "0.10", features = ["toml", "env", "yaml", "json"] }
serde = "1.0.136"
sysinfo = "0.23.10"

[workspace.package]
edition = "2021"