packages:
  - packages/*
  - config/*
  - website
  - i18n/*
  - '!**/test/**'
catalog:
  '@chromatic-com/storybook': ^3.2.2
  '@commitlint/cli': ^19.3.0
  '@eslint/js': ^9.15.0
  '@fontsource/jetbrains-mono': ^5.1.1
  '@mantine/core': ^7.15.2
  '@mantine/hooks': ^7.15.2
  '@mantine/carousel': ^7.15.2
  '@mantine/charts': ^7.15.2
  '@mantine/code-highlight': ^7.15.2
  '@mantine/dates': ^7.15.2
  '@mantine/dropzone': ^7.15.2
  '@mantine/form': ^7.15.2
  '@mantine/modals': ^7.15.2
  '@mantine/notifications': ^7.15.2
  '@mantine/nprogress': ^7.15.2
  '@mantine/spotlight': ^7.15.2
  '@mantine/tiptap': ^7.15.2
  '@storybook/addon-essentials': ^8.4.7
  '@storybook/addon-interactions': ^8.4.7
  '@storybook/addon-onboarding': ^8.4.7
  '@storybook/addon-styling-webpack': ^1.0.1
  '@storybook/blocks': ^8.4.7
  '@storybook/preview-api': ^8.4.7
  '@storybook/react': ^8.4.7
  '@storybook/react-vite': ^8.4.7
  '@storybook/test': ^8.4.7
  '@tabler/icons-react': ^2.47.0
  '@tauri-apps/api': ^2
  '@tauri-apps/cli': ^2
  '@tauri-apps/plugin-opener': ^2
  '@tiptap/extension-link': ^2.10.3
  '@tiptap/pm': ^2.10.3
  '@tiptap/react': ^2.10.3
  '@tiptap/starter-kit': ^2.10.3
  '@types/react': ^18.3.1
  '@types/react-dom': ^18.3.1
  '@types/node': ^22.10.2
  '@typescript-eslint/eslint-plugin': ^6.21.0
  '@typescript-eslint/parser': ^6.21.0
  '@vitejs/plugin-react-swc': ^3.7.2
  '@vitest/ui': ^1.6.0
  autoprefixer: ^10.4.19
  concurrently: ^9.1.0
  dayjs: ^1.11.13
  eslint-plugin-import: ^2.29.1
  eslint-plugin-prettier: ^5.1.3
  eslint-plugin-promise: ^6.2.0
  eslint-plugin-react-refresh: ^0.4.14
  globals: ^15.12.0
  husky: ^8.0.3
  i18next: ^23.16.8
  lint-staged: ^14.0.1
  lodash-es: ^4.17.21
  markdownlint: ^0.37.2
  mitt: ^3.0.1
  postcss-simple-vars: ^7.0.1
  prettier: ^3.3.2
  prettier-plugin-organize-imports: ^3.2.4
  prettier-plugin-packagejson: ^2.5.0
  prop-types: ^15.8.1
  react: ^18.3.1
  react-accessible-treeview: ^2.10.0
  react-devtools: ^4.28.5
  react-dom: ^18.3.1
  react-i18next: ^13.5.0
  react-scan: ^0.0.35
  recharts: ^2.14.1
  rimraf: ^5.0.7
  rollup-plugin-graph: ^2.0.0
  rollup-plugin-visualizer: ^5.12.0
  sass: ^1.77.6
  slate: ^0.112.0
  slate-history: ^0.110.3
  slate-hyperscript: ^0.100.0
  slate-react: ^0.112.0
  storybook: ^8.4.7
  storybook-dark-mode: ^4.0.2
  tailwindcss: ^3.4.4
  terser: ^5.31.1
  typescript-eslint: ^8.15.0
  ua-parser-js: ^1.0.39
  unplugin-turbo-console: ^1.10.6
  vite-plugin-dts: ^3.9.1
  vite-plugin-lib-inject-css: ^2.1.1
  vite-plugin-turbo-console: ^0.1.0
  vitest: ^1.6.0
  zustand: ^5.0.2
  vite: ^6.0.1
  typescript: ^5.7.2
  postcss: ^8.4.49
  postcss-preset-mantine: ^1.17.0
