packages:
  # all packages in direct subdirs of packages/
  - 'desktop'
  - 'components'
  - 'config/*'
  # all packages in subdirs of components/
  #  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
