[package]
name = "brainstorming_file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "1.0.0-alpha.118"
serde = "1.0.189"