[package]
name = "server"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "=0.5.0-rc.3"
rocket_okapi = "0.5"
schemars = "0.8.12"
okapi = { version = "0.7.0-rc.1"}