version: '3'
services:
  postgresql:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: rockie
      POSTGRES_PASSWORD: rockie
      POSTGRES_DB: rockie
    volumes:
      - postgresql:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '6379:6379'

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 1234567890
    command: server --console-address ":9001" /data
    restart: always
    volumes:
      - minio:/data
    ports:
      - '9000:9000'
      - '9001:9001'

volumes:
  postgresql:
  minio:
